### ISSUE TITLE
Implement syntax to remove a parent of a subtree with a hole

### ISSUE THREAD

**Issue by pollyvolk** [cqfn/astranaut#47]
It would be convenient to have an ability to specify a rule that would remove an nested parent of some branch of an AST. 
Such a parent may have various types of children. Therefore, they should be specified as holes.
An example is given below.

The source:
```mermaid
  graph TD;
      BinaryExpression -- 0 --> StringLiteral;
      BinaryExpression -- 1 --> EnclosedExpr;
      EnclosedExpr -- 0 --> Addition;
      Addition -- 0 --> Variable_a;
      Addition -- 1 --> Variable_b;
```

The target:

```mermaid
  graph TD;
      BinaryExpression -- 0 --> StringLiteral;
      BinaryExpression -- 1 --> Addition;
      Addition -- 0 --> Variable_a;
      Addition -- 1 --> Variable_b;
```

Syntax may be like:
`EnclosedExpr(#1) -> #1`

**Comment by kniazkov** [comment]
https://github.com/cqfn/astranaut/pull/55

**Comment by kniazkov** [comment]
@rultor release, tag is `0.2.2`
