### ISSUE TITLE
release to Maven Central

### ISSUE THREAD

**Issue by yegor256** [cqfn/astranaut#52]

**Comment by yegor256** [comment]
@pollyvolk you need to use parent pom from `jcabi-parent`, see how it's done for example here: https://github.com/objectionary/eo

**Comment by pollyvolk** [comment]
@rultor release, tag is 0.1

**Comment by yegor256** [comment]
@rultor release, tag is `0.1`

**Comment by kniazkov** [comment]
@rultor release, tag is 0.1

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1`

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1`

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1`

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1`

**Comment by yegor256** [comment]
@kniazkov try again, with version `0.1.1`

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1.1`

**Comment by kniazkov** [comment]
@rultor release, tag is 0.1.2

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1.2`

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1.2`

**Comment by yegor256** [comment]
@kniazkov try again, after my recent fix

**Comment by kniazkov** [comment]
@rultor release, tag is `0.1.4`

**Comment by kniazkov** [comment]
https://repo.maven.apache.org/maven2/org/cqfn/astranaut/

**Comment by yegor256** [comment]
@yegor256 great!
