### ISSUE TITLE
Implement API for using Astranaut as a library

### ISSUE THREAD

**Issue by pollyvolk** [cqfn/astranaut#61]
Currently the functionality of Astranaut may be accessed only from the CLI.
Users have requested the facility to use the project as a Java library.

**Comment by kniazkov** [comment]
@rultor release, tag is `0.2`

**Comment by pollyvolk** [comment]
Thank you. I am working on API usage guide now

**Comment by kniazkov** [comment]
@rultor release, tag is `0.2.1`
