### ISSUE TITLE
PMD violation in Adapter class: Avoid really long methods

### ISSUE THREAD

**Issue by pollyvolk** [cqfn/astranaut#69]
In the compiler mode, generation of a large number of rules related to some language produces a long method `init` in its Adapter class. 
Therefore, the following violation occurs: 
https://pmd.github.io/latest/pmd_rules_plsql_design.html#excessivemethodlength

Example:
[JavaAdapter.txt](https://github.com/cqfn/astranaut/files/9228968/JavaAdapter.txt)

Violation:
[INFO] PMD: D:\Documents\unified-ast\unified-ast\src\main\java\org\uast\uast\generated\tree\java\JavaAdapter.java[138-243]: Avoid really long methods. (ExcessiveMethodLength)

**Comment by kniazkov** [comment]
@pollyvolk Please attach the latest rules.dsl to reproduce the issue.

**Comment by pollyvolk** [comment]
[rules.txt](https://github.com/cqfn/astranaut/files/9240022/rules.txt)
@kniazkov
